version: "3.3"

services:
  api:
    build: ./
    volumes:
      - ./:/app
      - ./database.db:/database.db
    ports:
      - "80:80"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 80 # --reload

  data_processor:
    build: ./
    volumes:
      - ./:/app
      - ./database.db:/database.db
    command: python3 src/data_processor/main.py --frequency_sec=216000
